/*****************************************************************************************************************
PAWN Library Extension

Character typesv testing
ctype.inc
******************************************************************************************************************/
#if defined _PLE_CTYPET_INC
	#endinput
#else
	#define _PLE_CTYPET_INC
#endif

#if !defined _PLE_CONFIG_INC
	#include <PLE/config>
#endif

#include <PLE/ctype>
/*****************************************************************************************************************/
stock ctype_testing()
{
	//TO:DO
}
